GET http://localhost:3000/

###
# @name createOrder
POST http://localhost:3000/orders

{
    "items":[
      { "name": "Solero", "quantity": 1 },
      { "name": "Magnum", "quantity": 1 }
    ]
}
###

@id = {{createOrder.response.body.order.id}}
GET http://localhost:3000/orders/{{id}}

###

GET http://localhost:3000/sales

### 

POST http://localhost:3000/close
